### ISSUE TITLE
Update readme + book

### ISSUE THREAD

**Issue by RWOverdijk** [SpoonX/aurelia-acl#10]
The readme is old and says nothing. It also needs a book.

**Comment by matik12** [comment]
Hi @RWOverdijk,

please check out my plugin [aurelia-permission](https://github.com/matik12/aurelia-permission), which I have created during last weekend for the requirements of the project I am working on currently. I am curious about your feedback, because I believe that some of the ideas can be useful in any Aurelia application. Please note, that readMe file is incomplete is some areas and may not include  

Thanks and take care,
Mat

**Comment by RWOverdijk** [comment]
@matik12 I'm not sure why you post that on an issue. Are you interested in merging? In any case, If you want to contact me you can fine me here: https://gitter.im/spoonx/dev

**Comment by matik12** [comment]
@RWOverdijk this issue about readme info was hanging opened, so I decided to get touch with you and exchange thoughts related to app permission handling.

**Comment by RWOverdijk** [comment]
@matik12 I understand. This is just not the place to do it :) Feel free to hit me up on gitter though!

**Comment by matik12** [comment]
Yes, maybe it is not the best place, but I got a response from you very quickly and reminded you about this hanging readme issue :) 
What is more, anyone looking for more details related to this aurelia-acl plugin can find my link to see some of the ideas and based on both source codes can create something most suitable for him :)
